### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by lshaf** [jh0ker/mau_mau_bot#16]
I just start this bot today and got this error
```
Traceback (most recent call last):
  File "bot.py", line 32, in <module>
    from results import (add_call_bluff, add_choose_color, add_draw, add_gameinfo,
  File "D:\web-project\bbunobot\results.py", line 29, in <module>
    from utils import display_color, display_color_group, display_name
  File "D:\web-project\bbunobot\utils.py", line 26, in <module>
    from internationalization import _, __
  File "D:\web-project\bbunobot\internationalization.py", line 81, in <module>
    _ = _Underscore()
  File "D:\web-project\bbunobot\internationalization.py", line 43, in __init__
    in available_locales.keys()
  File "D:\web-project\bbunobot\internationalization.py", line 44, in <dictcomp>
    if locale != 'en_US'  # No translation file for en_US
TypeError: invalid file: None
```

I don't know what's it.

**Comment by jh0ker** [comment]
@lshaf Did you compile the gettext language files?

**Comment by lshaf** [comment]
what I was do just clone your git and then pip install telegram and pony. that's all.

**Comment by jh0ker** [comment]
@lshaf You gotta compile the .po files to .mo 

Just Google for it ^^

**Comment by lshaf** [comment]
so, I need to convert all lang to mo and put it at the same folder?

**Comment by jh0ker** [comment]
@lshaf Yes. Every MO should be in the same folder as the PO.

**Comment by lshaf** [comment]
nice, thanks. it works now and 1 more question.
how to make it run in background?

**Comment by jh0ker** [comment]
@lshaf If you're on Linux, there is a variety of programs you can use. I usually use tmux nowadays, but you can also use screen, nohup or run it as a service.

**Comment by lshaf** [comment]
thanks so much. it's running :laughing:

**Comment by jh0ker** [comment]
@lshaf Nice! Haha :D

**Comment by lshaf** [comment]
just found a problem again. when I play it and click the 1 of cards, it doesn't do anything.
I didn't found any error or something.

**Comment by jh0ker** [comment]
@lshaf You must activate inline feedback in botfather

**Comment by lshaf** [comment]
@jh0ker thanks again :laughing: 
I hope you can update README.md about installation
- Convert po to mo
- setinline and setinlinefeedback to botfather

**Comment by jh0ker** [comment]
@lshaf Done :)

**Comment by tasi788** [comment]
I have same problem at first
and I follow the guide
but i still got error like this
```
/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/python_telegram_bot-5.0.0-py3.5.egg/telegram/emoji.py:37: UserWarning: telegram.Emoji is being deprecated, please see https://git.io/v6DeB
Traceback (most recent call last):
  File "bot.py", line 32, in <module>
    from results import (add_call_bluff, add_choose_color, add_draw, add_gameinfo,
  File "/Users/user/Desktop/uno/mau_mau_bot/results.py", line 29, in <module>
    from utils import display_color, display_color_group, display_name
  File "/Users/user/Desktop/uno/mau_mau_bot/utils.py", line 26, in <module>
    from internationalization import _, __
  File "/Users/user/Desktop/uno/mau_mau_bot/internationalization.py", line 81, in <module>
    _ = _Underscore()
  File "/Users/user/Desktop/uno/mau_mau_bot/internationalization.py", line 43, in __init__
    in available_locales.keys()
  File "/Users/user/Desktop/uno/mau_mau_bot/internationalization.py", line 44, in <dictcomp>
    if locale != 'en_US'  # No translation file for en_US
TypeError: invalid file: None
```
I'm sure I had convert all po file to mo.

**Comment by lshaf** [comment]
@tasi788 it's different issue.
`telegram.Emoji is deprecated` so the code need to be updated.
