### ISSUE TITLE
Erro na inialização

### ISSUE THREAD

**Issue by Nilbertocs** [jh0ker/mau_mau_bot#36]
Ao tentar iniciar o bot retorna esses erros...

root@UnoBot:~/UnoBot# python bot.py
/root/UnoBot/telegram/emoji.py:37: UserWarning: telegram.Emoji is being deprecated, please see https://git.io/v6DeB
  warnings.warn("telegram.Emoji is being deprecated, please see https://git.io/v6DeB")
Traceback (most recent call last):
  File "bot.py", line 32, in <module>
    from results import (add_call_bluff, add_choose_color, add_draw, add_gameinfo,
  File "/root/UnoBot/results.py", line 29, in <module>
    from utils import display_color, display_color_group, display_name
  File "/root/UnoBot/utils.py", line 26, in <module>
    from internationalization import _, __
  File "/root/UnoBot/internationalization.py", line 24, in <module>
    from locales import available_locales
  File "/root/UnoBot/locales/__init__.py", line 21, in <module>
    from .available import available_locales
  File "/root/UnoBot/locales/available.py", line 30, in <module>
    available_locales = {'en_US': flag('US') + ' English (US)',
  File "/root/UnoBot/locales/available.py", line 27, in flag
    return chr(ord(code[0]) + OFFSET) + chr(ord(code[1]) + OFFSET)
ValueError: chr() arg not in range(256)

Alguém me ajuda a resolver pf

**Comment by jh0ker** [comment]
@Nilbertocs I don't speak spanish (spanish?) well enough to understand you, but the error looks like you might be using Python 2, which is not supported.

**Comment by jh0ker** [comment]
@Nilbertocs portuguese*

**Comment by Nilbertocs** [comment]
Sorry I was in a hurry, I ended up speaking in my native language, lol.
I solved what he said and now the second error happened.

`Traceback (most recent call last):
  File "bot.py", line 31, in <module>
    from results import (add_call_bluff, add_choose_color, add_draw, add_gameinfo,
  File "/home/nilbertocs4/mau_mau_bot/results.py", line 29, in <module>
    from utils import display_color, display_color_group, display_name
  File "/home/nilbertocs4/mau_mau_bot/utils.py", line 25, in <module>
    from internationalization import _, __
  File "/home/nilbertocs4/mau_mau_bot/internationalization.py", line 81, in <module>
    _ = _Underscore()
  File "/home/nilbertocs4/mau_mau_bot/internationalization.py", line 43, in __init__
    in available_locales.keys()
  File "/home/nilbertocs4/mau_mau_bot/internationalization.py", line 44, in <dictcomp>
    if locale != 'en_US'  # No translation file for en_US
TypeError: invalid file: None`

**Comment by jh0ker** [comment]
@Nilbertocs You forgot to process the translation files, please refer to the Readme on how to do that
