### ISSUE TITLE
ImportError: No module named 'telegram.contrib'

### ISSUE THREAD

**Issue by BadBoySeventeen** [jh0ker/mau_mau_bot#46]
```
[root@hno3 mau_mau_bot]# python3.4 bot.py
Traceback (most recent call last):
  File "bot.py", line 31, in <module>
    from results import (add_call_bluff, add_choose_color, add_draw, add_gameinfo,
  File "/root/mau_mau_bot/results.py", line 29, in <module>
    from utils import display_color, display_color_group, display_name
  File "/root/mau_mau_bot/utils.py", line 25, in <module>
    from internationalization import _, __
  File "/root/mau_mau_bot/internationalization.py", line 27, in <module>
    from shared_vars import gm
  File "/root/mau_mau_bot/shared_vars.py", line 22, in <module>
    from telegram.contrib.botan import Botan
ImportError: No module named 'telegram.contrib'
```

**my system is centos6.9,installed python3.4.**
**and what is botan,how can i install it?**
Thanks in advance.
@jh0ker

**Comment by BadBoySeventeen** [comment]
**Resolved, Reason:** The latest version of python-telegram-bot removed the botan module, causing the module to not be called normally
**Workaround:** Uninstall the latest version of python-telegram-bot and install version 7.0.1 and below
_Sometimes the envy of native speakers is English_
