### ISSUE TITLE
Bot is not responding after a player chooses a card

### ISSUE THREAD

**Issue by r33int** [jh0ker/mau_mau_bot#54]
Hello. I have installed this *awesome* bot on my server, but I got a weird issue with it. The bot seems to work flawlessly, however, when a player chooses a card after starting the game, the game completely frozes and will not go further.

System specs: 
Debian 8
Python 3.5.3

Logs:
![image](https://user-images.githubusercontent.com/22567851/36924360-940a1562-1e6e-11e8-9565-fffa25e684de.png)

Chat transcript:
![image](https://user-images.githubusercontent.com/22567851/36924417-c9ee2042-1e6e-11e8-8f6e-06010295b5ba.png)

I have tried disabling privacy mode for the bot, with no luck.

Thanks.

EDIT: I got new error lines, seems to be timeout.
`  File "/home/r33int/.local/lib/python3.5/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 617, in urlopen
    chunked=chunked)
  File "/home/r33int/.local/lib/python3.5/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 405, in _make_request
    exc_cls=ReadTimeoutError)
  File "/home/r33int/.local/lib/python3.5/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 321, in _raise_timeout
    raise exc_cls(*args)
telegram.vendor.ptb_urllib3.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=2.5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/r33int/Git/mau_mau_bot/utils.py", line 92, in send_async
    bot.sendMessage(*args, **kwargs)
  File "/home/r33int/.local/lib/python3.5/site-packages/telegram/bot.py", line 57, in decorator
    result = func(self, *args, **kwargs)
  File "/home/r33int/.local/lib/python3.5/site-packages/telegram/bot.py", line 82, in decorator
    result = self._request.post(url, data, timeout=kwargs.get('timeout'))
  File "/home/r33int/.local/lib/python3.5/site-packages/telegram/utils/request.py", line 272, in post
    **urlopen_kwargs)
  File "/home/r33int/.local/lib/python3.5/site-packages/telegram/utils/request.py", line 192, in _request_wrapper
    raise TimedOut()
telegram.error.TimedOut: Timed out
2018-03-02 23:09:19,728 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out
2018-03-02 23:09:19,729 - utils - ERROR - Timed out
NoneType: None
2018-03-02 23:09:57,021 - actions - INFO - XemTV (@Xemles) was skipped!.
2018-03-02 23:09:57,022 - actions - INFO - Started countdown for player: Enzo (@r33int). 100 seconds.`

**Comment by jh0ker** [comment]
Did you enable inline feedback with botfather? It needs both inline mode AND inline feedback to determine which card has been played

**Comment by r33int** [comment]
No, I forgot about this setting, now it works. Thanks!
