### ISSUE TITLE
internationalization.py  line 38

### ISSUE THREAD

**Issue by Sh1vam** [jh0ker/mau_mau_bot#90]
it gives error of this type:

\mau_mau_bot-master\internationalization.py", line 38, in <dictcomp>
    open(gettext.find(
TypeError: expected str, bytes or os.PathLike object, not NoneType

the code is:
    def __init__(self):
        self.translators = {
            locale: gettext.GNUTranslations(
                open(gettext.find(
                    GETTEXT_DOMAIN, GETTEXT_DIR, languages=[locale]
                ), 'rb')
            )
            for locale
            in available_locales.keys()
            if locale != 'en_US'  # No translation file for en_US
        }
        self.locale_stack = list()

**Comment by DO97** [comment]
More specifically, when this happens?

**Comment by Sh1vam** [comment]
> More specifically, when this happens?

when i was trying to run it on my PC

**Comment by retiolus** [comment]
same issue here
```
python3 bot.py
Traceback (most recent call last):
  File "bot.py", line 30, in <module>
    import settings
  File "/home/pi/unoplusbot/mau_mau_bot/settings.py", line 24, in <module>
    from utils import send_async
  File "/home/pi/unoplusbot/mau_mau_bot/utils.py", line 25, in <module>
    from internationalization import _, __
  File "/home/pi/unoplusbot/mau_mau_bot/internationalization.py", line 81, in <module>
    _ = _Underscore()
  File "/home/pi/unoplusbot/mau_mau_bot/internationalization.py", line 43, in __init__
    in available_locales.keys()
  File "/home/pi/unoplusbot/mau_mau_bot/internationalization.py", line 44, in <dictcomp>
    if locale != 'en_US'  # No translation file for en_US
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by jh0ker** [comment]
did you follow the instructions in the readme, specifically about compiling the translation files?

**Comment by retiolus** [comment]
> did you follow the instructions in the readme, specifically about compiling the translation files?

Yes

**Comment by jh0ker** [comment]
This error usually happens if you're missing a `.mo` file for one or more of your translations. Confirm that you have a `.mo` file for every `.po` file, eg. `locales/de_DE/LC_MESSAGES/unobot.mo`. If you added custom translations, they have to be added in the `locales/compile.sh` script.

I suggest you ensure you're not missing any commits from this repos `master` branch and re-compile all translations, eg.
```
cd locales
./compile.sh
```

**Comment by retiolus** [comment]
compile.sh didn't work for me, made it with the full command... problem fixed! Wasn't executing the command inside the locales folder.

**Comment by jofg123** [comment]
Same issue in compiling

**Comment by jofg123** [comment]
It didn't work the compile.sh

**Comment by DO97** [comment]
I'm not having any issue following the instructions.
